version: '2'
services:

    instance1-webapollo:
      image: ebiokit/docker-webapollo
      container_name: instance1-webapollo
      environment:
        - APOLLO_ADMIN_EMAIL=admin@local.host
        - APOLLO_ADMIN_PASSWORD=password
        - APOLLO_ADMIN_FIRST_NAME=Ad
        - APOLLO_ADMIN_LAST_NAME=min
        # Optional, do not change
        - WEBAPOLLO_DB_HOST=webapollo-db
        - WEBAPOLLO_DB_PORT=5432
        - WEBAPOLLO_DB_NAME=postgres
        - WEBAPOLLO_DB_USERNAME=postgres
        - WEBAPOLLO_DB_PASSWORD=mysecretpassword
        - WEBAPOLLO_CHADO_DB_HOST=webapollo-chado
        - WEBAPOLLO_CHADO_DB_PORT=5432
        - WEBAPOLLO_CHADO_DB_NAME=postgres
        - WEBAPOLLO_CHADO_DB_USERNAME=postgres
        - WEBAPOLLO_CHADO_DB_PASSWORD=mysecretpassword
      links:
        - instance1-webapollo-postgres:webapollo-db
        - instance1-webapollo-chado:webapollo-chado
      depends_on:
        - instance1-webapollo-data
      volumes_from:
        - instance1-webapollo-data
      ports:
        - "8888:8080"

    instance1-webapollo-postgres:
      image: postgres
      container_name: instance1-webapollo-postgres
      environment:
        - POSTGRES_PASSWORD=mysecretpassword
        - PGDATA=/data/postgresql
      depends_on:
        - instance1-webapollo-data
      volumes_from:
        - instance1-webapollo-data

    instance1-webapollo-chado:
      image: postgres
      container_name: instance1-webapollo-chado
      environment:
        - POSTGRES_PASSWORD=mysecretpassword
        - PGDATA=/data/chado
      depends_on:
        - instance1-webapollo-data
      volumes_from:
        - instance1-webapollo-data

    instance1-webapollo-data:
      image: busybox
      container_name: instance1-webapollo-data
      volumes:
        - /home/foo/dockers/webapollo/data:/data
