version: '2'
services:

    instance1-webapollo:
      image: ebiokit/docker-webapollo
      container_name: instance1-webapollo
      environment:
        - WEBAPOLLO_DB_HOST=postgres-machine
        - CHADO_DB_HOST=postgres-machine
        - APOLLO_ADMIN_EMAIL=ebiokit@gmail.com
        - APOLLO_ADMIN_PASSWORD=supersecret
      links:
        - instance1-webapollo-postgres:postgres-machine
      depends_on:
        - instance1-webapollo-data
      volumes_from:
        - instance1-webapollo-data
      ports:
        - "8888:8080"

    instance1-webapollo-postgres:
      image: postgres
      container_name: instance1-webapollo-postgres
      environment:
        - PGDATA=/data/postgresql
      depends_on:
        - instance1-webapollo-data
      volumes_from:
        - instance1-webapollo-data

    instance1-webapollo-data:
      image: busybox
      container_name: instance1-webapollo-data
      volumes:
        - /home/foo/dockers/webapollo/data:/data
